# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            HARP Grant Program
tagline:          
description:      'A grant program that aims to get incoming college students living in the residence halls more active and able in their communities.'
url:              http://harpgrantprogram.github.io

author:           
  name:           
  url:            

paginate:         5

# Custom vars

github:
  repo:           https://github.com/harpgrantprogram/harpgrantprogram.github.io
  baseurl: /harpgrantprogram.github.io
